import Head from "next/head";

import React from "react";

import Container from "@jokejunction/layout/Container/Container";
import { useRouter } from "next/router";

import Page from "@jokejunction/layout/Page";
import JokeEditView from "@jokejunction/views/JokeEditView";

export default function EditJoke() {
  const router = useRouter();

  const data = {
    title: "Road Trips",
    author: "melis@we.com",
    body: "This is a joke",
    views: 100,
    createdAt: 1623421317413,
    id: 1,
  };

  return (
    <>
      <Head>
        <title>Edit Joke</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page>
        <main>
          <Container>
            <JokeEditView heading="Edit Joke" jokeData={data} />
          </Container>
        </main>
      </Page>
    </>
  );
}
