import Head from "next/head";
import { dehydrate, QueryClient, useQuery } from "@tanstack/react-query";

import Container from "@jokejunction/layout/Container/Container";
import DashboardView from "@jokejunction/views/DashboardView";
import Page from "@jokejunction/layout/Page";

import { getJokes } from "@jokejunction/utils/api";
import { JOKE_PAGINATE_KEY } from "@jokejunction/utils/queryKeys";

export default function Dashboard() {
  const { data } = useQuery(JOKE_PAGINATE_KEY(["1", "5"]), getJokes);

  return (
    <>
      <Head>
        <title>Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page>
        <main>
          <Container>
            <DashboardView jokes={data} />
          </Container>
        </main>
      </Page>
    </>
  );
}

export async function getStaticProps() {
  const queryClient = new QueryClient();

  await queryClient.prefetchQuery([JOKE_PAGINATE_KEY(["1", "5"])], () =>
    getJokes(1, 5)
  );
  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
}
