import Head from "next/head";
import Container from "@jokejunction/layout/Container/Container";
import Page from "@jokejunction/layout/Page";
import JokeEditView from "@jokejunction/views/JokeEditView";

export default function CreateJoke() {
  return (
    <>
      <Head>
        <title>Create New</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page>
        <main>
          <Container>
            <JokeEditView heading="Create New Joke" />
          </Container>
        </main>
      </Page>
    </>
  );
}
